//DO NOT EDIT THIS FILE!!!!!
#include<iostream>
#ifndef ARRAYMODIFY_H
#define ARRAYMODIFY_H

//num is size of the array.
void printArray(int *arr, int num);

//num is size of the array.
void arrayModify(int *arr, int num);

#endif

